// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdMRXCedZYut57rhdSI9lEcwYK8GNVCPA',
    appId: '1:288251664691:web:22718be586109fd1e20646',
    messagingSenderId: '288251664691',
    projectId: 'mazad-79c3d',
    authDomain: 'mazad-79c3d.firebaseapp.com',
    storageBucket: 'mazad-79c3d.appspot.com',
    measurementId: 'G-N82T9P90KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXQuY5M2_G6sPcuJ7bsuEaqAOvz7KClA',
    appId: '1:288251664691:android:473d0825932d80fae20646',
    messagingSenderId: '288251664691',
    projectId: 'mazad-79c3d',
    storageBucket: 'mazad-79c3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3nN786fWAI-3aBOK7CbUgZcC3jZ8wEg',
    appId: '1:288251664691:ios:2b9a0468cae642d7e20646',
    messagingSenderId: '288251664691',
    projectId: 'mazad-79c3d',
    storageBucket: 'mazad-79c3d.appspot.com',
    iosClientId: '288251664691-9j0oh2s8hj2q8kl47098ciqp22qm1s6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN3nN786fWAI-3aBOK7CbUgZcC3jZ8wEg',
    appId: '1:288251664691:ios:a6ba5659f8ec3334e20646',
    messagingSenderId: '288251664691',
    projectId: 'mazad-79c3d',
    storageBucket: 'mazad-79c3d.appspot.com',
    iosClientId: '288251664691-3hedkbn0cp2g6f07psknqtarh05d3opv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazad.RunnerTests',
  );
}
